FROM golang:1.10-alpine as builder
RUN apk update && \
    apk add git
WORKDIR /go/src/kafka-test
COPY go/src/kafka-test .
RUN go get -d -v
RUN go install -v

FROM alpine
COPY --from=builder \
     /go/bin/kafka-test /kafka-test
CMD ["/kafka-test"]
